version: 2.1

executors:
  android-flutter:
    docker:
      - image: gmemstr/flutter-fastlane:latest
jobs:
  beta_deploy:
    executor: android-flutter
    steps:
      - checkout
      # - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > key.jks
      # - run: echo "$PLAY_STORE_UPLOAD_KEY_INFO" | base64 --decode > android/key.properties
      - run: whoami
      - run: cd final && fastlane beta

workflows:
  deploy:
    jobs:
      - beta_deploy