version: 2.1

executors:
  android-flutter:
    docker:
      - image: contactekansh/android-fastlane:0.1
jobs:
  build:
    executor: android-flutter
    steps:
      - checkout
      - run: chmod -R 777 /root/project
      - run: export ANDROID_SDK_ROOT=/opt/android-sdk
      - run: cd final && gem install bundler:1.17.3 && bundle install && bundle exec fastlane build
  beta_deploy:
    executor: android-flutter
    steps:
      - checkout
      - run: chmod -R 777 /root/project
      - run: export ANDROID_SDK_ROOT=/opt/android-sdk
      - run: cd final && gem install bundler:1.17.3 && bundle install && bundle exec fastlane beta
  deploy:
    executor: android-flutter
    steps:
      - checkout
      - run: chmod -R 777 /root/project
      - run: export ANDROID_SDK_ROOT=/opt/android-sdk
      - run: cd final && gem install bundler:1.17.3 && bundle install && bundle exec fastlane deploy

workflows:
  deploy:
    jobs:
      - build:
            filters:
              branches:
                only:
                    - dev
      - beta_deploy:
            filters:
              branches:
                only:
                    - staging
            requires:
              - build
      - deploy:
            filters:
              branches:
                only:
                    - master