version: 2.1

executors:
  android-flutter:
    docker:
      - image: contactekansh/android-fastlane:0.1
jobs:
  beta_deploy:
    executor: android-flutter
    steps:
      - checkout
      # - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > key.jks
      # - run: echo "$PLAY_STORE_UPLOAD_KEY_INFO" | base64 --decode > android/key.properties
      # - run: whoami
      # - run: chown -R cirrus:cirrus /home/cirrus/project
      - run: cd final && bundle exec fastlane beta

workflows:
  deploy:
    jobs:
      - beta_deploy